pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'scheduler'
            args '-v /scheduler/app:app'
        }
    }
    stages {
        stage('test') {
            steps {
                dir("scheduler") {
                    sh 'python run_tests.py'
                }
            }
        }
    }
}